### PR TITLE
Port samplerate to python 3.4

### PR DESCRIPTION
**Pull request by gregorias**
This pull request ports samplerate to python 3.4 standard making it usable by both python 3 and python 2 users. It also updates cython _samplerate.c file.

Do you think you might accept it and push it to pypi?

### CODE REVIEW

**Comment by Marvin182** [comment]
Push, please merge this!

**Comment by ThomasLecocq** [comment]
@gregorias @Marvin182 : I don't use Python 3.x so do you confirm this PR actually works on Py 3.4 and doens't break anything on Py>2.6 ?

**Comment by gregorias** [comment]
Yes, It is conformant to python3 changes and maintains backward compatibility with python2.

**Comment by Marvin182** [comment]
Well I get a little bit confused, which one is the 'official' repository?
https://github.com/cournape/samplerate or https://github.com/ThomasLecocq/samplerate ?

And why does the pull request has 7 commits?
Actually only f3f7b76 is required. I reviewed it and it looks fine to me. It works both with Python 2.7 and Python 3.5, while the current release (0.3.3 in PyPi) fails for Python 3+.

Therefor I would appreciate a 0.3.4 with those changes.

Btw. thank you gregorias :)

**Comment by ThomasLecocq** [comment]
@Marvin182 : this is the official one, mine is just a hack to setup.cfg in order to install it straight on many ubuntu 64 machines (otherwise fails miserably by not finding the libs)... @cournape added me to the dev list of this repo, so I can discuss & accept PR. But @cournape : you'll need to build & up to pypi !

I don't know why this has 7 commits while #f3f7b76 is the only relevant.

**Pull request merged**
